sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root
  alioos:
    endpoint: oss-cn-guangzhou.aliyuncs.com
    bucket-name: sky-take-out552
  redis:
    host: localhost
    port: 6379
    password: root
    database: 10
  wechat:
    app-id: wx046455d3d236404a
    app-secret: 1fe1b81134e3bd6a6d0f7edebb4964cb